-- AlterTable
ALTER TABLE "User" ALTER COLUMN "languages" SET DEFAULT ARRAY[]::TEXT[],
ALTER COLUMN "interests" SET DEFAULT ARRAY[]::TEXT[],
ALTER COLUMN "mentoringGoals" SET DEFAULT ARRAY[]::TEXT[],
ALTER COLUMN "skillsOffered" SET DEFAULT ARRAY[]::TEXT[],
ALTER COLUMN "skillsWanted" SET DEFAULT ARRAY[]::TEXT[],
ALTER COLUMN "mentoringTypes" SET DEFAULT ARRAY[]::TEXT[];
